
[functions.kopioh-bot]
enabled = true
verify_jwt = false
import_map = "./functions/kopioh-bot/deno.json"
entrypoint = "./functions/kopioh-bot/index.ts"
static_files = [ 
  # "./functions/kopioh-bot/*.html", 
  "./functions/kopioh-bot/locales/"
  ]
