[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[functions.kopio-bot]
enabled = true
verify_jwt = false
import_map = "./functions/kopio-bot/deno.json"
entrypoint = "./functions/kopio-bot/index.ts"
static_files = [ 
  "./functions/kopio-bot/locales/*/*.ftl"
  ]
